[workspace]
members = [
    "rust/template",
    "rust/template/cmd_parser",
    "rust/template/differential_datalog",
    "rust/template/distributed_datalog",
    "rust/template/ovsdb",
    "rust/ddlog_derive",
]
exclude = ["test/"]
