[package]
name = "differential_datalog"
version = "0.1.0"

[dependencies.graph_map]
git="https://github.com/frankmcsherry/graph-map.git"

[dev-dependencies]
getopts="0.2.14"
rand="0.3.13"
byteorder="0.4.2"
itertools="^0.6"

[dependencies]
differential-dataflow = "0.9"
abomonation = "0.7.2"
timely = "0.9"
fnv="1.0.2"
num = "0.2"
serde = "1.0"
serde_derive = "1.0"
libc = "0.2"
sequence_trie = "0.3"

[features]
default = []

[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false
debug-assertions = false

[lib]
name = "differential_datalog"
path = "./lib.rs"
