[package]
name = "datalog_example"
version = "0.1.0"

build = "build.rs"

[build-dependencies]
libtool = "0.1"

[dependencies.differential_datalog]
path = "./differential_datalog"

[dependencies.cmd_parser]
path = "./cmd_parser"

[dependencies.ddlog_ovsdb_adapter]
path = "./ovsdb"

[dependencies]
abomonation= { git = "https://github.com/frankmcsherry/abomonation" }
serde = "1.0.14"
serde_derive = "1.0.14"
fnv="1.0.2"
libc="0.2"
time="0.1"
twox-hash="1.1"
rustop="1.0.2"
cpuprofiler = "0.0.3"

[features]
default = []

[profile.release]
opt-level = 2
debug = false
rpath = false
lto = false
debug-assertions = false

<<<<<<< HEAD
=======
[lib]
name = "datalog_example_ddlog"
path = "./lib.rs"
crate-type = ["cdylib", "rlib", "staticlib"]

>>>>>>> master
[[bin]]

name = "datalog_example_cli"
path = "./main.rs"

# [lib] section must be in the ned

[lib]
name = "datalog_example_ddlog"
path = "./lib.rs"
# Compiler will append the crate-type attribute here
# crate-type = ["rlib", "staticlib"]
